doctrine_migrations:
    migrations_paths:
        # The namespace is arbitrary but must differ from App\Migrations,
        # because migration classes are not autoloaded.
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
